config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    resources :members
    resources :positions
  end
  root to: "teams#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :team
  has_one :position, through: :team

  include PgSearch
  pg_search_scope :global_search,
    against: [ :phone ],
    associated_against: {
      team: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :members, dependent: :destroy
  has_many :positions

  # include PgSearch
  # pg_search_scope :global_search,
  #   against: [ :name ],
  #   associated_against: {
  #     members: [ :phone ]
  #   },
  #    using: {
  #     tsearch: { prefix: true }
  #   }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :update, :edit, :destroy]
  before_action :set_team, only: [:index, :new, :create, :destroy, :show, :edit, :update]

  def index
    @members = Member.all
  end

  def create
    @member = Member.new(member_params)
    @member.team = @team
    if @member.save
      redirect_to team_path(@team), notice: 'The member was successfully created.'
    else
      render :new
    end
  end

  def new
    @member = Member.new
  end

  def edit
    @positions = Position.all
    # @member.position = @position
  end

  def show
    @member.team = @team
  end

  def update
    if @member.update(member_params)
      redirect_to team_path(@team)
    else
      render :edit
    end
  end

  def destroy
    @member.team = @team
    @member.destroy
    redirect_to team_path(@team)
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def set_team
    @team = Team.find_by_id(params[:team_id])
  end

  def member_params
    params.require(:member).permit(:name, :phone, :email, :team_id)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :update, :edit, :destroy]
  before_action :set_team, only: [:index, :new, :create, :destroy, :show, :edit, :update]

  def index
    @positions = Position.all
  end

  def create
    @position = Position.new(position_params)
    @position.team = @team
    if @position.save
      redirect_to team_path(@team), notice: 'Position was successfully created.'
    else
      render :new
    end
  end

  def new
    @position = Position.new
  end

  def edit
  end

  def show
    @position.team = @team
  end

  def update
    if @position.update(position_params)
      redirect_to team_path(@team)
    else
      render :edit
    end
  end

  def destroy
    @member.team = @team
    @position.destroy
    redirect_to team_path(@team)
  end

  private

  def position_params
    params.require(:position).permit(:name, :team_id)
  end

  def set_position
    @position = Position.find(params[:id])
  end

  def set_team
    @team = Team.find_by_id(params[:team_id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to @team, notice: 'Team was successfully created.'
    else
      render :new
    end
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def show
    @team = Team.find(params[:id])
  end

  def update
    if @team.update(team_params)
      redirect_to team_path(@team)
    else
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_path
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/jpg" href="<%= image_url('favicon.png') %>" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>

  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
</html>

app/views/members/_form.html.erb
<%= simple_form_for [@team, @member] do |f| %>
  <%= f.input :name %>
  <%= f.input :positions, collection: @positions %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/members/edit.html.erb
<div class="container">
  <h1>Edit [ <%= @member.name.upcase %> ]</h1>
  <%= render 'form' %>
  <%= link_to 'Back', team_path(@team) %>
</div>

<%= content_for(:title, @member.name + 'TEAM UP | Edit ') %>

app/views/members/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h3>Members:</h3>
  <br>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Position</th>
        <th>Phone</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @team.members.order(name: :asc).each do |member| %>
        <tr>
          <td><%= member.name.upcase %></td>
          <td><%= member.position %></td>
          <td><%= member.phone %></td>
          <td><%= member.email %></td>
          <td><%= link_to 'Show', team_path(@team), class: "btn btn-link" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="show-team-links">
    <%= link_to 'Add New Member', new_team_member_path(@team), class: "btn btn-info" %>
    <%= link_to 'Back to Team List', teams_path, class: "btn btn-info" %>
  </div>
</div>

<%= content_for(:title, 'TEAM UP') %>

app/views/members/new.html.erb
<div class='container'>
  <h1>New Member</h1>
  <%= render 'form' %>
</div>

<%= content_for(:title, 'Add a Member | TEAM UP') %>

app/views/members/show.html.erb
<div class='container'>
  <h2><strong><%= @member.name.upcase %></strong></h2>
  <br>
  <table>
    <tbody>
      <tr>
        <td><h3><i class="fa fa-street-view" aria-hidden="true"></i></h3></td>
        <td><h3><%= @member.positions.name %></h3></td>
      </tr>
      <tr>
        <td><h3><i class="fa fa-mobile" aria-hidden="true"></i></h3></td>
        <td><h3><%= @member.phone %></h3></td>
      </tr>
      <tr>
        <td><h3><i class="fa fa-envelope-o" aria-hidden="true"></i></h3></td>
        <td><h3><%= @member.email %></h3></td>
      </tr>
    </tbody>
  </table>
  <div class="show-team-links">
    <%= link_to 'Back', @team, class: "btn btn-primary" %>
  </div>
</div>

<%= content_for(:title, @member.name + ' | TEAM UP') %>

app/views/positions/_form.html.erb
<%= simple_form_for [@team, @position] do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/positions/edit.html.erb
<h1>this is a position edit page</h1>

app/views/positions/index.html.erb
<h1>this is a positions index page</h1>

app/views/positions/new.html.erb
<div class="container">
  <h1>New Position</h1>
  <%= render 'form' %>
</div>

<%= content_for(:title, 'Add Position | TEAM UP') %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <div class="navbar-logo">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "favicon.png" %>
    <% end %>
  </div>

  <!-- search bar -->
  <div class='navbar-right'>
    <div class="search">
      <%= form_tag teams_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          placeholder: 'Enter Phone Number',
          class: 'search-box'
        %>
        <button class="btn btn-default btn-search" %>
          SEARCH
        </button>
      <% end %>
    </div>

  <!-- Add a new team -->
    <div class='navbar-add'>
      <%= link_to "ADD TEAM", new_team_path, class: "navbar-link" %>
    </div>
  </div>
</div>